version: '3.8'

services:
  twitch-chat-analyzer:
    image: dlepe/twitch-chat-analyzer
    build:
      context: .
      args:
        - ARG_TIMEZONE=America/Los_Angeles
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - REDIS_HOSTNAME=redis
      - REDIS_PASSWORD=
    depends_on:
      - redis
  redis:
    container_name: "redis"
    image: redislabs/redistimeseries:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
