version: '3.8'

services:
  service:
    image: dlepe/twitch-chat-analyzer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y"
    ports:
      - "8080:8080"
      - "8000:8000"
