version: '3.4'

services:
  twitch-chat-analyzer:
    image: dlepe/twitch-chat-analyzer
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - localstack
  localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME-localstack-twitchchatanalyzer}"
      image: localstack/localstack
      network_mode: bridge
      ports:
        - "127.0.0.1:4566:4566"
      environment:
        - SERVICES=dynamodb
        - DATA_DIR=${DATA_DIR-}
        - DOCKER_HOST=unix:///var/run/docker.sock
      volumes:
        - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
