version: '3.8'

services:
  twitch-chat-analyzer:
    image: dlepe/twitch-chat-analyzer
    build:
      context: .
      args:
        - ARG_TIMEZONE=America/Los_Angeles
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local # Need to update this to work for CI/CD processes
    depends_on:
      - localstack
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-twitchchatanalyzer}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=${DATA_DIR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # justlog:    
  #     image: dlepe/justlog:arm64
  #     network_mode: bridge
  #     ports:
  #       - "127.0.0.1:8025:8025"    
  #     volumes:        
  #       - "$(pwd)/config.json:/etc/justlog.json" # TODO - define a config directory to read from
  #       - "/Volumes/USB-Drive/logs:/logs dlepe/justlog-arm" # TODO - update the volume folder
