version: '3.8'

services:
  twitch-chat-analyzer:
    image: dlepe/twitch-chat-analyzer
    build:
      context: .
      args:
        - ARG_TIMEZONE=America/Los_Angeles
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOSTNAME=redis
    depends_on:
      - redis
  redis:
    container_name: "redis"
    image: redis:7-alpine3.15
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass REDIS_PASSWORD
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
