twitch-chat-analyzer:
  log-api:
    base-url: "https://logs.ivr.fi"
  twitch-helix-api:
    base-url: "https://api.twitch.tv/helix"

logging:
  level:
    com:
      dlepe:
        twitchchatanalyzer: DEBUG
