# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "corretto"
          cache: maven
      - name: Inject client id into the properties file
        run: perl -pi -e 's/TWITCH_CLIENT_ID/"$ENV{TWITCH_CLIENT_ID}"/' ./src/main/resources/application.yml
        env:
          TOKEN: ${{ secrets.TWITCH_CLIENT_ID }}
      - name: Inject client secret into the properties file
        run: perl -pi -e 's/TWITCH_CLIENT_SECRET/"$ENV{TWITCH_CLIENT_SECRET}"/' ./src/main/resources/application.yml
        env:
          TOKEN: ${{ secrets.TWITCH_CLIENT_SECRET }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
