# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "corretto"
          cache: maven
      - name: Inject client id into the properties file
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "TWITCH_CLIENT_ID"
          replace: "$CLIENT_ID"
          regex: false
          include: "**application.yml"
        env:
          CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      - name: Inject client secret into the properties file
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "TWITCH_CLIENT_SECRET"
          replace: "$CLIENT_SECRET"
          regex: false
          include: "**application.yml"
        env:
          CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
